name: app_akademie
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  http: ^1.1.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  fluentui_icons: ^1.0.0
  shimmer: ^3.0.0
  loading_indicator: ^3.1.1
  percent_indicator: ^4.2.3
  flutter_launcher_icons: ^0.9.2
  image_picker: ^1.0.4
  multiple_images_picker: ^1.0.1
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.0.0
  fluttertoast: ^8.2.2
  colorful_safe_area: ^1.0.0
  icon_forest: ^1.1.8
  stacked_notification_cards: ^0.1.0-dev.4
  flutter_speed_dial: ^7.0.0
  theme_provider: ^0.6.0
  flutter_theme_provider: ^0.0.4
  animated_theme_switcher: ^2.0.8
  path_provider: ^2.1.0
  path: ^1.8.3
  auto_size_text: ^3.0.0
  flutter_svg: ^1.0.3
  flutter_image: ^4.1.8
  logger: ^2.0.2
  foundation: ^0.0.5
  rflutter_alert: ^2.0.7
  line_icons: ^2.0.3
  image_stack: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6


flutter_icons:
  ios: true
  android: true
  remove_alpha_icons: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/check_icon.png
    - assets/images/error_image.png
    - lib/task_solutions/0_1_Collections/G_/Group_App/assets/grueeneblaetter.jpg
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
